// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCde_FjInWoOWdYdYldk3yCT_aoDyUfOjU',
    appId: '1:838552672492:web:b8ecc559b3d2338714adc9',
    messagingSenderId: '838552672492',
    projectId: 'fitassist-1bc95',
    authDomain: 'fitassist-1bc95.firebaseapp.com',
    storageBucket: 'fitassist-1bc95.firebasestorage.app',
    measurementId: 'G-RVVY8DW1QZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA2adEAwzWJX3jTtILGeTtGkKW4l6dM5M',
    appId: '1:838552672492:android:958f87d271aab14814adc9',
    messagingSenderId: '838552672492',
    projectId: 'fitassist-1bc95',
    storageBucket: 'fitassist-1bc95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_WoAfxDr0oaih43BIvTZoph3MPqsQXBs',
    appId: '1:838552672492:ios:460a2bcb07ca809514adc9',
    messagingSenderId: '838552672492',
    projectId: 'fitassist-1bc95',
    storageBucket: 'fitassist-1bc95.firebasestorage.app',
    iosBundleId: 'com.example.fitAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_WoAfxDr0oaih43BIvTZoph3MPqsQXBs',
    appId: '1:838552672492:ios:460a2bcb07ca809514adc9',
    messagingSenderId: '838552672492',
    projectId: 'fitassist-1bc95',
    storageBucket: 'fitassist-1bc95.firebasestorage.app',
    iosBundleId: 'com.example.fitAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCde_FjInWoOWdYdYldk3yCT_aoDyUfOjU',
    appId: '1:838552672492:web:d0830a881d82f68e14adc9',
    messagingSenderId: '838552672492',
    projectId: 'fitassist-1bc95',
    authDomain: 'fitassist-1bc95.firebaseapp.com',
    storageBucket: 'fitassist-1bc95.firebasestorage.app',
    measurementId: 'G-4HZWGHN7KK',
  );
}
